Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
w1 = BandsPlotWidget(bands=[data1], dos=data2, plot_fermilevel = True, show_legend = True, energy_range = {"ymin": -13.0, "ymax": 10.0})
display(w1)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn [3], line 1[0m
[0;32m----> 1[0m w1 [38;5;241m=[39m [43mBandsPlotWidget[49m[43m([49m[43mbands[49m[38;5;241;43m=[39;49m[43m[[49m[43mdata1[49m[43m][49m[43m,[49m[43m [49m[43mdos[49m[38;5;241;43m=[39;49m[43mdata2[49m[43m,[49m[43m [49m[43mplot_fermilevel[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mshow_legend[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43menergy_range[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43m{[49m[38;5;124;43m"[39;49m[38;5;124;43mymin[39;49m[38;5;124;43m"[39;49m[43m:[49m[43m [49m[38;5;241;43m-[39;49m[38;5;241;43m13.0[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mymax[39;49m[38;5;124;43m"[39;49m[43m:[49m[43m [49m[38;5;241;43m10.0[39;49m[43m}[49m[43m)[49m
[1;32m      2[0m display(w1)

File [0;32m/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/widget_bandsplot/bandsplot.py:79[0m, in [0;36mBandsPlotWidget.__init__[0;34m(self, bands, dos, fermi_energy, show_legend, plot_fermilevel, energy_range)[0m
[1;32m     76[0m [38;5;28mself[39m[38;5;241m.[39mdos_fermienergy [38;5;241m=[39m dos[[38;5;124m'[39m[38;5;124mfermi_energy[39m[38;5;124m'[39m]
[1;32m     77[0m temp_dos [38;5;241m=[39m deepcopy(dos)
[0;32m---> 79[0m [38;5;28mself[39m[38;5;241m.[39mtdos_x [38;5;241m=[39m [43mdos[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mtdos[39;49m[38;5;124;43m'[39;49m[43m][49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mx[39;49m[38;5;124;43m'[39;49m[43m][49m
[1;32m     80[0m [38;5;28mself[39m[38;5;241m.[39mtdos_y [38;5;241m=[39m dos[[38;5;124m'[39m[38;5;124mtdos[39m[38;5;124m'[39m][[38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m]
[1;32m     82[0m tx [38;5;241m=[39m np[38;5;241m.[39marray([38;5;28mself[39m[38;5;241m.[39mtdos_x)

[0;31mKeyError[0m: 'x'
KeyError: 'x'

